### ISSUE TITLE
Add Guessing Game file in CPP

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/GuessingGame#1]
Make sure this before making PR regarding it :

-> Appropriate title for PR
-> Making another branch with an appropriate name.
-> Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by adityaomar3** [comment]
Hey I would like to solve this issue.

**Comment by Arpitgupta1014** [comment]
Hey @adityaomar3 , include bits file in the code as well.

**Comment by flow6979** [comment]
hey @Arpitgupta1014 can you please assign this to me?

**Comment by Arpitgupta1014** [comment]
Good job @adityaomar3

**Comment by flow6979** [comment]
@Arpitgupta1014 please create more issues like this so that i can contribute.
thank you.
