### ISSUE TITLE
Add Guessing Game file in python with proper code

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/GuessingGame#2]
Make sure this before making PR regarding it :

-> Appropriate title for PR
-> Making another branch with an appropriate name.
-> Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by singhAman05** [comment]
can i work in this problem @Arpitgupta1014

**Comment by WaniAthar** [comment]
can i contribute to this? @Arpitgupta1014

**Comment by Arpitgupta1014** [comment]
Good work @singhAman05
